### ISSUE TITLE
v1.1.0 Roadmap

### ISSUE THREAD

**Issue by wassgha** [wassgha/digital-signage#1]
### Planned features

- [ ] Support for multiple displays
- [ ] Set up utility for configuring the database connection and the main user credentials
- [ ] User management (invitation/roles)
- [ ] General documentation
- [ ] Documentation on adding widgets
- [ ] Implementing a testing infrastructure
- [ ] OTA updates
- [ ] Security audit
- [ ] More widgets (Calendar, Menu, RSS feed, etc.)
